monitor:
  name: 7T
  width: 69  # width of monitor (in cm)
  distance: 196  # distance of participant from monitor (in cm)
  gamma: 2.1  # specific value for gamma correction
  verbose: True

window:
  size: [1920, 1080]
  screen: 1
  pos: [0, 0]
  color: [0, 0, 0]
  fullscr: True
  winType: pyglet
  waitBlanking: True

eyetracker:
  address: '100.1.1.1'
  dot_size: 0.1  # in deg
  options:
    calibration_type: HV5

stimuli:
  fixation_width: 6
  fixation_color: [1,-1,-1]
  text_color: [-1,1,-1]

design:
  n_trials: 14 # total nr of blocks for all events
  randomize: False
  start_duration: 0
  end_duration: 30
  static_isi: 30
  stim_duration: 30

various:
  piechart_width: 1
  text_width: 150
  text_height: 0.5
  buttons: ['b', 'e', 'j', 'k', 'l', 'semicolon']
  button_size: 2
